### ISSUE TITLE
[FEAT] 집 상세 조회 기능

### ISSUE THREAD

**Issue by Jeongseokjin** [woorifisa-projects-3rd/woori-zip-BE#10]
💬 기능 설명
 > 집 상세 조회하는 기능 구현하기

🎯 구현 내용
 - [x] HouseDetailResponse DTO 구현
 - [x] HouseService 구현
 - [x] HouseController 구현
 - [x] Postman json 더미데이터 조회 완료

**Comment by rlfrkdms1** [comment]
석진님 기능 설명에 **집 목록**을 조회한다고 되어 있는데, **집 상세**라고 바꿔주셔야 될 것 같아요 ~

**Comment by Jeongseokjin** [comment]
네 가은님 update 했습니다~
